name: "Marshall Mallicoat"
markdown: redcarpet
redcarpet:
  extensions: ['smart']		#smartypants extension (--- for em dash, etc.)
highlighter: 'pygments'		#was "pygments: 'true'" but Jekyll changed name
source: ~/Documents/Blog/Source
# paginate: 3
destination: ~/Documents/Blog/Site		# default is ./_site
# future: false			#will build all posts, not just future-dated ones
