name: "Marshall Mallicoat"
markdown: redcarpet
redcarpet:
  extensions: ['smart']		#smartypants extension (--- for em dash, etc.)
highlighter: 'pygments'		#was "pygments: 'true'" but Jekyll changed name
source: /Users/user/Documents/Blog
paginate: 3
#destination: ./_site		#unnecessary, since this is by default
#future: false				#will build all posts, not just future-dated ones
